maze_version: 1

parking_areas: [[[4.0, 12.4], [5.6, 14.4], [5.6, 15.6], [4.0, 13.6]],
                [[4.0, 14.4], [5.6, 16.4], [5.6, 17.6], [4.0, 15.6]],
                [[4.0, 16.4], [5.6, 18.4], [5.6, 19.6], [4.0, 17.6]]]
parking_waiting_goal_pose: [3, 6]
parking_waiting_goal_dir: 1.57  # up
parking_goal_dir: 0.785         # right up

speed_goal_pose: [2, 14]
speed_goal_orientation: 1.57

cell_sz: 2
maze_target_x: 1
maze_target_y: 2
