
TebLocalPlannerROS:
    odom_topic: odom
    map_frame: map

    # Trajectory

    teb_autosize: True
    dt_ref: 0.3
    dt_hysteresis: 0.1
    global_plan_overwrite_orientation: True
    max_global_plan_lookahead_dist: 5.0
    feasibility_check_no_poses: 4
    allow_init_with_backwards_motion: True

    # Robot
         
    wheelbase: 0.340
    cmd_angle_instead_rotvel: True

    max_vel_x: 0.486
    max_vel_x_backwards: 0.486
    # For fast
    # max_vel_x: 0.8
    # max_vel_x_backwards: 0.8

    max_vel_theta: 0.36
    acc_lim_x: 0.03
    acc_lim_theta: 0.03
    # Just to avoid too high turn
    min_turning_radius: 0.9
    footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "polygon"
        # radius: 0.3 # for type "circular"
        # line_start: [-0.16, 0.0] # for type "line"
        # line_end: [0.16, 0.0] # for type "line"
        # front_offset: 0.2 # for type "two_circles"
        # front_radius: 0.2 # for type "two_circles"
        # rear_offset: 0.2 # for type "two_circles"
        # rear_radius: 0.2 # for type "two_circles"
        vertices: [ [0.45, 0.15], [-0.125, 0.15], [-0.125, -0.15], [0.45, -0.15] ] # for type "polygon"

    # GoalTolerance

    xy_goal_tolerance: 0.15
    yaw_goal_tolerance: 0.05
    free_goal_vel: False

    # Obstacles
    min_obstacle_dist: 0.4

    include_costmap_obstacles: True
    costmap_obstacles_behind_robot_dist: 1.0
    obstacle_poses_affected: 5
    # costmap_converter_plugin: ""
    # costmap_converter_spin_thread: True
    # costmap_converter_rate: 5

    global_plan_viapoint_sep: 0.1
    # Optimization

    no_inner_iterations: 5
    no_outer_iterations: 4
    optimization_activate: True
    optimization_verbose: False
    penalty_epsilon: 0.01
    weight_max_vel_x: 2
    weight_max_vel_theta: 1
    weight_acc_lim_x: 1
    weight_acc_lim_theta: 1
    weight_kinematics_nh: 1000
    weight_kinematics_forward_drive: 1
    weight_kinematics_turning_radius: 10
    weight_optimaltime: 50
    weight_obstacle: 50
    weight_viapoint: 0.1

    weight_dynamic_obstacle: 10 # not in use yet
    # selection_alternative_time_cost: False # not in use yet

    # Homotopy Class Planner

    enable_homotopy_class_planning: False
    enable_multithreading: True
    simple_exploration: False
    max_number_classes: 4
    roadmap_graph_no_samples: 15
    roadmap_graph_area_width: 5
    h_signature_prescaler: 0.5
    h_signature_threshold: 0.1
    obstacle_keypoint_offset: 0.1
    obstacle_heading_threshold: 0.45
    visualize_hc_graph: False
